# Generated by Django 2.0.1 on 2018-01-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_face_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='description',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(upload_to='faces/'),
        ),
    ]
